root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./bin/main.exe ./cmd/api"
bin = "bin\\main.exe"

include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]

delay = 1000
log = "build-errors.log"
stop_on_error = true
